config/routes.rb
Rails.application.routes.draw do

  resources :paychecks, :employees
  
  root 'paychecks#index'
  delete 'paycheck/:id', to: "paychecks#destroy"
  get 'paychecks', to: "paychecks#destroy"

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :paychecks
end

app/models/paycheck.rb
class Paycheck < ActiveRecord::Base
  belongs_to :employee
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :wage, :marital_status, :fica, :fwh, :swh, :claims)
    end
end

app/controllers/paychecks_controller.rb
class PaychecksController < ApplicationController
  before_action :set_paycheck, only: [:show, :edit, :update, :destroy]

  # GET /paychecks
  # GET /paychecks.json
  def index
    @paychecks = Paycheck.all
  end

  # GET /paychecks/1
  # GET /paychecks/1.json
  def show
  end

  # GET /paychecks/new
  def new
    @paycheck = Paycheck.new
  end

  # GET /paychecks/1/edit
  def edit
  end

  # POST /paychecks
  # POST /paychecks.json
  def create
    @paycheck = Paycheck.new(paycheck_params)

    respond_to do |format|
      if @paycheck.save
        format.html { redirect_to @paycheck, notice: 'Paycheck was successfully created.' }
        format.json { render :show, status: :created, location: @paycheck }
      else
        format.html { render :new }
        format.json { render json: @paycheck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paychecks/1
  # PATCH/PUT /paychecks/1.json
  def update
    respond_to do |format|
      if @paycheck.update(paycheck_params)
        format.html { redirect_to @paycheck, notice: 'Paycheck was successfully updated.' }
        format.json { render :show, status: :ok, location: @paycheck }
      else
        format.html { render :edit }
        format.json { render json: @paycheck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paychecks/1
  # DELETE /paychecks/1.json
  def destroy
    @paycheck.destroy
    respond_to do |format|
      format.html { redirect_to paychecks_url, notice: 'Paycheck was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paycheck
      @paycheck = Paycheck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paycheck_params
      params.require(:paycheck).permit(:employee_id, :name, :paycheck, :start_date, :end_date, :total_hours_worked, :gross_wages, :total_deductions, :net_wages)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/paychecks_helper.rb
module PaychecksHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :wage %><br>
    <%= f.text_field :wage %>
  </div>
  <div class="field">
    <%= f.label :marital_status %><br>
    <%= f.text_field :marital_status %>
  </div>
  <div class="field">
    <%= f.label :fica %><br>
    <%= f.text_field :fica %>
  </div>
  <div class="field">
    <%= f.label :fwh %><br>
    <%= f.text_field :fwh %>
  </div>
  <div class="field">
    <%= f.label :swh %><br>
    <%= f.text_field :swh %>
  </div>
  <div class="field">
    <%= f.label :claims %><br>
    <%= f.number_field :claims %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Wage</th>
      <th>Marital Status</th>
      <th>Fica</th>
      <th>Fwh</th>
      <th>Swh</th>
      <th>Claims</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.wage %></td>
        <td><%= employee.marital_status %></td>
        <td><%= employee.fica %></td>
        <td><%= employee.fwh %></td>
        <td><%= employee.swh %></td>
        <td><%= employee.claims %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Wage:</strong>
  <%= @employee.wage %>
</p>

<p>
  <strong>Marital status:</strong>
  <%= @employee.marital_status %>
</p>

<p>
  <strong>Fica:</strong>
  <%= @employee.fica %>
</p>

<p>
  <strong>Fwh:</strong>
  <%= @employee.fwh %>
</p>

<p>
  <strong>Swh:</strong>
  <%= @employee.swh %>
</p>

<p>
  <strong>Claims:</strong>
  <%= @employee.claims %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimplePayroll</title>
<<<<<<< HEAD
=======
  <%= javascript_include_tag 'jquery_ujs' %>
>>>>>>> 5e1201181a922d761a1f2071058c0c200fc7ea7e
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/paychecks/_form.html.erb
<%= form_for(@paycheck) do |f| %>
  <% if @paycheck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paycheck.errors.count, "error") %> prohibited this paycheck from being saved:</h2>

      <ul>
      <% @paycheck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :employee_id %><br>
    <%= f.number_field :employee_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :paycheck %><br>
    <%= f.text_field :paycheck %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :total_hours_worked %><br>
    <%= f.text_field :total_hours_worked %>
  </div>
  <div class="field">
    <%= f.label :gross_wages %><br>
    <%= f.text_field :gross_wages %>
  </div>
  <div class="field">
    <%= f.label :total_deductions %><br>
    <%= f.text_field :total_deductions %>
  </div>
  <div class="field">
    <%= f.label :net_wages %><br>
    <%= f.text_field :net_wages %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paychecks/edit.html.erb
<h1>Editing paycheck</h1>

<%= render 'form' %>

<%= link_to 'Show', @paycheck %> |
<%= link_to 'Back', paychecks_path %>

app/views/paychecks/index.html.erb
<h1>Listing paychecks</h1>

<table>
  <thead>
    <tr>
      <th>Employee</th>
      <th>Name</th>
      <th>Paycheck</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Total hours worked</th>
      <th>Gross wages</th>
      <th>Total deductions</th>
      <th>Net wages</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paychecks.each do |paycheck| %>
      <tr>
        <td><%= paycheck.employee_id %></td>
        <td><%= paycheck.name %></td>
        <td><%= paycheck.paycheck %></td>
        <td><%= paycheck.start_date %></td>
        <td><%= paycheck.end_date %></td>
        <td><%= paycheck.total_hours_worked %></td>
        <td><%= paycheck.gross_wages %></td>
        <td><%= paycheck.total_deductions %></td>
        <td><%= paycheck.net_wages %></td>
        <td><%= link_to 'Show', paycheck %></td>
        <td><%= link_to 'Edit', edit_paycheck_path(paycheck) %></td>
        <td><%= link_to 'Destroy', paycheck, :method => :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paycheck', new_paycheck_path %>

app/views/paychecks/new.html.erb
<h1>New paycheck</h1>

<%= render 'form' %>

<%= link_to 'Back', paychecks_path %>

app/views/paychecks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee:</strong>
  <%= @paycheck.employee_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @paycheck.name %>
</p>

<p>
  <strong>Paycheck:</strong>
  <%= @paycheck.paycheck %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @paycheck.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @paycheck.end_date %>
</p>

<p>
  <strong>Total hours worked:</strong>
  <%= @paycheck.total_hours_worked %>
</p>

<p>
  <strong>Gross wages:</strong>
  <%= @paycheck.gross_wages %>
</p>

<p>
  <strong>Total deductions:</strong>
  <%= @paycheck.total_deductions %>
</p>

<p>
  <strong>Net wages:</strong>
  <%= @paycheck.net_wages %>
</p>

<%= link_to 'Edit', edit_paycheck_path(@paycheck) %> |
<%= link_to 'Back', paychecks_path %>